### ISSUE TITLE
Header tag

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/vue-ui-components#31]
Add components for:
- H1 tags
- Paragraph tags

**Comment by hvitis** [comment]
Hello @ninetteadhikari 

Could you specify the requirements? I'm a bit confused since I don't know how customised those components should be.
As per the Element library we use there is a [header component](https://element.eleme.io/#/en-US/component/page-header) but there is no paragraph template.
How should we customise the paragraph one?

**Comment by ninetteadhikari** [comment]
Hey @hvitis sorry this one is a bit confusing. The idea was to standardize the texts with certain font weights, size etc. But I am not myself what that would look like 😅 i don’t think this is a priority and I’ll add more details later on.. Maybe you can help with other tickets like pagination?

**Comment by hvitis** [comment]
Sure! Pagination done, PR on the way. I will move to other issues then. Feel free to move this one back for specification! 
Thanks
